# Generated by Django 4.0.3 on 2022-03-12 17:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('address_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.address')),
                ('country_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.country')),
            ],
        ),
        migrations.CreateModel(
            name='StoreSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('store_domain', models.TextField()),
                ('user_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.userrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('filename', models.ImageField(upload_to='')),
                ('store_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.storesession')),
            ],
        ),
        migrations.CreateModel(
            name='RequestedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('name', models.TextField()),
                ('type', models.TextField()),
                ('quantity', models.IntegerField()),
                ('row_number', models.IntegerField()),
                ('store_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.storesession')),
            ],
        ),
    ]
