# Generated by Django 4.0.3 on 2022-03-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_alter_screenshot_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemprice',
            name='row_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemprice',
            name='type',
            field=models.TextField(default='meds'),
            preserve_default=False,
        ),
    ]
