# Generated by Django 4.0.3 on 2022-03-15 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_itemprice_row_number_itemprice_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screenshot',
            old_name='filename',
            new_name='image',
        ),
    ]
