# Generated by Django 4.0.3 on 2022-03-15 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_rename_filename_screenshot_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='itemprice',
            options={'verbose_name': 'Item Pricing Record', 'verbose_name_plural': 'Item Pricing Records'},
        ),
        migrations.AlterModelOptions(
            name='requesteditem',
            options={'verbose_name': 'Requested Item', 'verbose_name_plural': 'Requested Items'},
        ),
        migrations.AlterModelOptions(
            name='screenshot',
            options={'verbose_name': 'Store Basket Screenshot Record', 'verbose_name_plural': 'Store Basket Screenshot Records'},
        ),
        migrations.AlterModelOptions(
            name='storesession',
            options={'verbose_name': 'Store Session Record', 'verbose_name_plural': 'Store Session Records'},
        ),
        migrations.AlterModelOptions(
            name='userrequest',
            options={'verbose_name': 'User Request Record', 'verbose_name_plural': 'User Request Records'},
        ),
    ]
