# Generated by Django 4.0.3 on 2022-03-23 19:46

import api_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_alter_address_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=api_app.models.LowercaseCharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
